language: python
python: 
  - "2.7"
install:
    - pip install -r requirements.txt
script:
  - find |grep CloudStack
  - PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-package/Users/larstobi/Library/Python/2.7/site-packages/
  - python -c "import sys;print sys.path"
  - nosetests
