language: python
sudo: required
python: 
  - "2.7"
install:
    - pip install -r requirements.txt
script:
  - export PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/Users/larstobi/Library/Python/2.7/site-packages/
  - nosetests
