#!/usr/bin/env python

import sys

sys.path.append('./lib/')
import flockr.config as config
import flockr.cmdline as cmdline
import flockr.control as control

cfg = config.Config('flockr.yaml')
cmd = cmdline.CmdLine()
ctl = control.Control()

ctl.run(cmd.get_options())
